import {
  Activity,
  Archive,
  ArchiveRestore,
  Atom,
  Bluetooth,
  BookOpen,
  Boxes,
  Braces,
  Bug,
  CircuitBoard,
  ClipboardList,
  Container,
  Database,
  Download,
  Feather,
  Fish,
  Flame,
  Gamepad2,
  Gauge,
  GitBranch,
  GraduationCap,
  Hammer,
  History,
  KeyRound,
  LayoutDashboard,
  LayoutGrid,
  LogIn,
  Monitor,
  Package,
  PackageSearch,
  Paintbrush,
  PanelLeft,
  Power,
  Printer,
  Rocket,
  Scale,
  Server,
  Shapes,
  ShieldCheck,
  SlidersHorizontal,
  Sparkles,
  SquareTerminal,
  Star,
  Store,
  Terminal,
  Type,
  Users,
  Volume2,
  Wifi,
  Wine,
} from 'lucide-react'
import type { LucideIcon } from 'lucide-react'

export const ICONS: Record<string, LucideIcon> = {
  intro: BookOpen,
  preparation: ClipboardList,
  installation: Download,
  'first-boot': Power,
  'basic-config': SlidersHorizontal,
  users: Users,
  pacman: Package,
  aur: PackageSearch,
  network: Wifi,
  audio: Volume2,
  gpu: CircuitBoard,
  desktop: Monitor,
  kde: Shapes,
  gnome: Sparkles,
  hyprland: Boxes,
  sway: PanelLeft,
  i3: LayoutGrid,
  xfce: Feather,
  'display-managers': LogIn,
  terminal: SquareTerminal,
  bash: Terminal,
  zsh: Braces,
  fish: Fish,
  starship: Star,
  fonts: Type,
  git: GitBranch,
  ssh: KeyRound,
  bluetooth: Bluetooth,
  printers: Printer,
  storage: Database,
  btrfs: Database,
  snapshots: History,
  docker: Container,
  virtualization: Server,
  gaming: Gamepad2,
  steam: Store,
  wine: Wine,
  proton: Atom,
  security: ShieldCheck,
  firewall: Flame,
  backups: ArchiveRestore,
  optimization: Gauge,
  customization: Paintbrush,
  troubleshooting: Bug,
  expert: GraduationCap,
}

export const TOOL_ICONS: Record<string, LucideIcon> = {
  dashboard: LayoutDashboard,
  builder: Hammer,
  compare: Scale,
  'status-checker': Activity,
}

export function getIcon(name: string): LucideIcon {
  return ICONS[name] ?? TOOL_ICONS[name] ?? Package
}
