import {
  Activity,
  Archive,
  ArchiveRestore,
  ArrowLeftRight,
  Atom,
  Bluetooth,
  BookOpen,
  Boxes,
  Braces,
  Bug,
  CircuitBoard,
  ClipboardList,
  Cloud,
  Container,
  Database,
  Download,
  Feather,
  Fish,
  Flame,
  Gamepad2,
  Gauge,
  GitBranch,
  GitMerge,
  Globe,
  GraduationCap,
  Hammer,
  HardDrive,
  Hash,
  History,
  KeyRound,
  LayoutDashboard,
  LayoutGrid,
  Lock,
  LogIn,
  Monitor,
  Network,
  Package,
  PackageSearch,
  Paintbrush,
  PanelLeft,
  Power,
  Printer,
  RefreshCw,
  Repeat,
  Rocket,
  Route,
  Scale,
  Server,
  Shapes,
  Share2,
  ShieldAlert,
  ShieldCheck,
  SlidersHorizontal,
  Sparkles,
  SquareTerminal,
  Star,
  Store,
  Terminal,
  Type,
  Users,
  Volume2,
  Wifi,
  Wine,
  Wrench,
} from 'lucide-react'
import type { LucideIcon } from 'lucide-react'

export const ICONS: Record<string, LucideIcon> = {
  intro: BookOpen,
  preparation: ClipboardList,
  installation: Download,
  'first-boot': Power,
  'basic-config': SlidersHorizontal,
  users: Users,
  pacman: Package,
  aur: PackageSearch,
  apt: Archive,
  apk: HardDrive,
  network: Wifi,
  audio: Volume2,
  gpu: CircuitBoard,
  desktop: Monitor,
  kde: Shapes,
  gnome: Sparkles,
  hyprland: Boxes,
  sway: PanelLeft,
  i3: LayoutGrid,
  xfce: Feather,
  'display-managers': LogIn,
  terminal: SquareTerminal,
  bash: Terminal,
  zsh: Braces,
  fish: Fish,
  starship: Star,
  fonts: Type,
  git: GitBranch,
  ssh: KeyRound,
  bluetooth: Bluetooth,
  printers: Printer,
  storage: Database,
  btrfs: Database,
  snapshots: History,
  docker: Container,
  virtualization: Server,
  gaming: Gamepad2,
  steam: Store,
  wine: Wine,
  proton: Atom,
  security: ShieldCheck,
  firewall: Flame,
  backups: ArchiveRestore,
  optimization: Gauge,
  customization: Paintbrush,
  troubleshooting: Bug,
  expert: GraduationCap,
  'net-fundamentos': Network,
  'net-ipv4': Hash,
  'net-ipv6': Globe,
  'net-switching': ArrowLeftRight,
  'net-stp': RefreshCw,
  'net-routing': Route,
  'net-igp': Share2,
  'net-ospf': GitMerge,
  'net-bgp': Cloud,
  'net-nat': Repeat,
  'net-servicios': Server,
  'net-seguridad': Lock,
  'db-fundamentos': Database,
  'db-modelado': Shapes,
  'db-sql': Braces,
  'db-sql-avanzado': Boxes,
  'db-postgresql': Server,
  'db-mariadb': HardDrive,
  'db-admin': Wrench,
  'db-seguridad': ShieldAlert,
}

export const TOOL_ICONS: Record<string, LucideIcon> = {
  dashboard: LayoutDashboard,
  builder: Hammer,
  compare: Scale,
  'status-checker': Activity,
}

export function getIcon(name: string): LucideIcon {
  return ICONS[name] ?? TOOL_ICONS[name] ?? Package
}
